apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ip2g3xqyt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ip2g3xqyt-python 
  name: ip2g3xqyt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ip2g3xqyt-python 
